# Rubocop configuration for deprecate gem
AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'test_manual.rb'
    - 'vendor/**/*'
    - 'test/**/*'  # Exclude all test files from most checks

# Relax line length for readability
Layout/LineLength:
  Max: 120
  Exclude:
    - 'deprecate.gemspec'

# Don't require documentation for simple gems
Style/Documentation:
  Enabled: false

# Allow longer methods for main functionality
Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

# Allow complex methods for core functionality
Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

# Allow long blocks in tests
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

# Allow long classes in tests
Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

# Don't require frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

# Allow format strings (used in deprecation messages)
Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

# Allow string literals as needed
Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    - 'spec/**/*'

# Don't require MFA for development
Gemspec/RequireMFA:
  Enabled: false

# Allow development dependencies in gemspec
Gemspec/DevelopmentDependencies:
  Enabled: false

# Allow deprecated gemspec attributes for compatibility
Gemspec/DeprecatedAttributeAssignment:
  Enabled: false

# Allow encoding comments for compatibility
Style/Encoding:
  Enabled: false

# Allow redundant return for clarity
Style/RedundantReturn:
  Enabled: false