name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2', '3.3']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    - name: Run tests
      run: |
        bundle exec rspec
    
    - name: Run manual verification
      run: |
        bundle exec ruby -I lib test_manual.rb

  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Ruby  
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    
    - name: Try alternative Qlty installation
      run: |
        # Try npm installation as fallback
        npm install -g @qlty/cli || true
        # Try different download URL
        curl -fsSL https://get.qlty.sh | bash || true
        # Try with wget
        wget -qO- https://install.qlty.sh | bash || true
        # Check if any installation worked
        which qlty || echo "Qlty installation failed - skipping quality checks"
        qlty --version || echo "Qlty not available"
        qlty check --reporter github-actions || echo "Quality checks skipped"
      continue-on-error: true

  gem:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1  
      with:
        ruby-version: '3.3'
        bundler-cache: true
    
    - name: Build gem
      run: gem build deprecate.gemspec
    
    - name: Install gem locally
      run: gem install ./deprecate-*.gem